version: "3.8"

volumes:
  data:

networks:
  cortex:
    driver: bridge

services:
  cortex-engine:
    image: ghcr.io/canner/cortex-engine:${cortex_ENGINE_VERSION}
    pull_policy: always
    platform: ${PLATFORM}
    ports:
      - ${cortex_ENGINE_SQL_PORT}:${cortex_ENGINE_SQL_PORT}
      - ${cortex_ENGINE_PORT}:${cortex_ENGINE_PORT}
    volumes:
      - ./etc:/usr/src/app/etc
    networks:
      - cortex

  ibis-server:
    image: ghcr.io/canner/cortex-engine-ibis:${IBIS_SERVER_VERSION}
    pull_policy: always
    platform: ${PLATFORM}
    ports:
      - ${IBIS_SERVER_PORT}:${IBIS_SERVER_PORT}
    environment:
      cortex_ENGINE_ENDPOINT: http://cortex-engine:${cortex_ENGINE_PORT}
      LOG_LEVEL: DEBUG
    networks:
      - cortex

  qdrant:
    image: qdrant/qdrant:v1.11.0
    pull_policy: always
    ports:
      - 6333:6333
      - 6334:6334
    networks:
      - cortex

  cortex-ui:
    image: ghcr.io/canner/cortex-ui:${cortex_UI_VERSION}
    pull_policy: always
    platform: ${PLATFORM}
    environment:
      DB_TYPE: sqlite
      # /app is the working directory in the container
      SQLITE_FILE: /app/data/db.sqlite3
      cortex_ENGINE_ENDPOINT: http://cortex-engine:${cortex_ENGINE_PORT}
      cortex_AI_ENDPOINT: http://host.docker.internal:${cortex_AI_SERVICE_PORT}
      IBIS_SERVER_ENDPOINT: http://ibis-server:${IBIS_SERVER_PORT}
      GENERATION_MODEL: ${GENERATION_MODEL}
      # telemetry
      cortex_ENGINE_PORT: ${cortex_ENGINE_PORT}
      cortex_AI_SERVICE_VERSION: ${cortex_AI_SERVICE_VERSION}
      cortex_UI_VERSION: ${cortex_UI_VERSION}
      cortex_ENGINE_VERSION: ${cortex_ENGINE_VERSION}
      USER_UUID: ${USER_UUID}
      POSTHOG_API_KEY: ${POSTHOG_API_KEY}
      POSTHOG_HOST: ${POSTHOG_HOST}
      TELEMETRY_ENABLED: ${TELEMETRY_ENABLED}
      # client side
      NEXT_PUBLIC_USER_UUID: ${USER_UUID}
      NEXT_PUBLIC_POSTHOG_API_KEY: ${POSTHOG_API_KEY}
      NEXT_PUBLIC_POSTHOG_HOST: ${POSTHOG_HOST}
      NEXT_PUBLIC_TELEMETRY_ENABLED: ${TELEMETRY_ENABLED}
      # configs
      cortex_PRODUCT_VERSION: ${cortex_PRODUCT_VERSION}

    ports:
      - ${cortex_UI_PORT}:3000
    volumes:
      - ./etc:/app/data
    networks:
      - cortex
    depends_on:
      - cortex-engine
      - ibis-server

  postgres:
    image: postgres:14-alpine
    platform: ${PLATFORM}
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - cortex
