##### Dependancies used in this kustomization:
# nginx.ingress
# external-dns
# cert-manager
# kubectl kustomize

#test output like this:
#kubectl kustomize deployment/kustomizations --enable-helm > deployment/kustomizations/cortexai.kustimized.yaml
#kubectl create namespace cortex
#kubectl apply -f deployment/kustomizations/cortexai.kustimized.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace for all resources here and in the Helm charts
namespace: cortex
helmCharts:

### Uncomment if you are planing to use postgresql
  - name: postgresql
    repo: https://repo.vmware.com/bitnami-files
    version: 15.5.5
    releaseName: cortex-postgresql
    valuesFile: helm-values_postgresql_15.yaml
    includeCRDs: true
    # the Same Namespace
    namespace: cortex

  - name: qdrant
    repo: https://qdrant.github.io/qdrant-helm
    version: 1.11.0
    releaseName: cortex-qdrant
    valuesFile: helm-values-qdrant_1.11.0.yaml
    includeCRDs: true
    # The Same Namespace
    namespace: cortex


images:
  # for the latest versions, please check here: https://github.com/Canner/CortexAI/blob/main/docker/.env.example#L23
  - name: ghcr.io/canner/cortex-bootstrap
    newTag: 0.1.5 # cortex_BOOTSTRAP_VERSION
  - name: ghcr.io/canner/cortex-engine
    newTag: 0.14.8 # cortex_ENGINE_VERSION
  - name: ghcr.io/canner/cortex-ui
    newTag: 0.24.1 # cortex_UI_VERSION
  - name: ghcr.io/canner/cortex-ai-service
    newTag: 0.19.7 # cortex_AI_SERVICE_VERSION
  - name: ghcr.io/canner/cortex-engine-ibis
    newTag: 0.14.8 # IBIS_SERVER_VERSION

resources:
  - base/cm.yaml
  - base/deploy-cortex-ui.yaml
  - base/deploy-cortex-engine.yaml
  - base/deploy-cortex-ibis-server.yaml
  - base/deploy-cortex-ai-service.yaml
  - base/pvc.yaml
  - base/svc.yaml
### Modify these examples first and uncomment them:
  # - examples/ingress-cortex_example.yaml
  # - examples/certificate-cortex_example.yaml
### Usually you do not need to generate a certificate for Qdrant
#  - examples/certificate-qdrant_example.yaml
### Best practice is to create and deploy Secrets manually, not as part of kustomization or GitOps!
#  - examples/secret-cortex_example.yaml